/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dryseed_ndkapplication_NdkJniUtils */

#ifndef _Included_dryseed_ndkapplication_NdkJniUtils
#define _Included_dryseed_ndkapplication_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dryseed_ndkapplication_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dryseed_ndkapplication_NdkJniUtils_getCLanguageString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
